'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const L=require('../assets/i18n.js'),locales=require('../assets/locales.js'),PF=require('../assets/planner.js'),Project=require('../assets/project.js');
let count=0;function test(name,run){run();console.log('PASS',name);count++;}
test('Exactly Russian, Kazakh and English are selectable',()=>assert.deepEqual([...L.supported],['ru','kk','en']));
test('Both translation dictionaries cover identical messages and placeholders',()=>{assert.deepEqual(Object.keys(locales.en).sort(),Object.keys(locales.kk).sort());for(const key of Object.keys(locales.en))for(const lang of ['en','kk']){assert(locales[lang][key].trim(),key);assert.deepEqual((locales[lang][key].match(/\{\d+\}/g)||[]).sort(),(key.match(/\{\d+\}/g)||[]).sort(),key);}});
test('Visible labels switch among all languages',()=>{L.setLanguage('ru');assert.equal(L.s('Сохранить проект'),'Сохранить проект');L.setLanguage('en');assert.equal(L.s('Сохранить проект'),locales.en['Сохранить проект']);L.setLanguage('kk');assert.equal(L.s('Сохранить проект'),locales.kk['Сохранить проект']);});
test('Template interpolation never translates user data',()=>{L.setLanguage('en');const source=['<span>Артикул</span><b>','</b>'];assert.equal(L.tpl(source,'Сохранить проект'),'<span>'+locales.en['Артикул']+'</span><b>Сохранить проект</b>');});
test('Language-sensitive maps do not cache their first translation',()=>{const names=L.labels({dashboard:'Обзор'});L.setLanguage('en');assert.equal(names.dashboard,locales.en['Обзор']);L.setLanguage('kk');assert.equal(names.dashboard,locales.kk['Обзор']);});
test('Markup localizes labels without touching control names or data values',()=>{L.setLanguage('en');const result=L.s('<label>Остаток<input name="Остаток" value="Остаток" placeholder="Неизвестен"></label>');assert(result.includes('name="Остаток" value="Остаток"'));assert(result.includes('<label>'+locales.en['Остаток']));assert(result.includes('placeholder="'+locales.en['Неизвестен']+'"'));});
test('Dynamic diagnostic values survive translation',()=>{const key='Количество должно быть не меньше {0} и кратно {1}.';for(const lang of ['en','kk']){L.setLanguage(lang);assert.equal(L.message('Количество должно быть не меньше 12 и кратно 6.'),locales[lang][key].replace('{0}','12').replace('{1}','6'));}});
test('Changing language leaves calculation, edits and approvals unchanged',()=>{const data=PF.demo(),state={data,cfg:{...PF.defaults,categories:{},asOf:data.snapshot},edits:{demo0:60},approved:new Set(['Поставщик А']),sheets:[],errors:[],audit:[],lastCalc:new Date()};const stable=()=>{const p=JSON.parse(Project.encode(state));delete p.savedAt;return JSON.stringify(p);};const before=stable(),quantities=PF.calculate(data,state.cfg).map(r=>r.order);for(const lang of L.supported){L.setLanguage(lang);assert(stable()===before,'Language changed serialized business data');assert.deepEqual(PF.calculate(data,state.cfg).map(r=>r.order),quantities);assert(state.approved.has('Поставщик А'));}});
test('Invalid language input is rejected',()=>{L.setLanguage('ru');for(const value of ['fr','__proto__',{},null])assert.throws(()=>L.setLanguage(value));assert.equal(L.getLanguage(),'ru');});
test('Preference persists separately from the project and survives reload',()=>{const storage=new Map();const context={PFLocales:locales,localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)}};const code=fs.readFileSync(path.join(__dirname,'../assets/i18n.js'),'utf8');vm.runInNewContext(code,context);context.PFLang.setLanguage('kk');vm.runInNewContext(code,context);assert.equal(context.PFLang.getLanguage(),'kk');assert.deepEqual([...storage.keys()],['procureflow.language']);});
test('Blocked local storage does not prevent language selection',()=>{const context={PFLocales:locales,localStorage:{getItem:()=>{throw Error('blocked');},setItem:()=>{throw Error('blocked');}}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../assets/i18n.js'),'utf8'),context);context.PFLang.setLanguage('en');assert.equal(context.PFLang.getLanguage(),'en');});
test('Language assets load before application scripts',()=>{const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');assert(html.indexOf('assets/locales.js')<html.indexOf('assets/i18n.js'));assert(html.indexOf('assets/i18n.js')<html.indexOf('assets/app.js'));});
L.setLanguage('ru');console.log(count+' localization tests passed.');
